// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUUJAp2pc32SPJZnYrx5E3Za2KC2dnvkQ',
    appId: '1:233610521690:android:33349846e003efc8c33c63',
    messagingSenderId: '233610521690',
    projectId: 'e-survey-3b1f8',
    storageBucket: 'e-survey-3b1f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM7Yp8ut1OJc0qKZEAS43TMSRb6gM0MJs',
    appId: '1:233610521690:ios:8d7dd15181c27a21c33c63',
    messagingSenderId: '233610521690',
    projectId: 'e-survey-3b1f8',
    storageBucket: 'e-survey-3b1f8.appspot.com',
    iosClientId: '233610521690-5qb1vivvo77qodjvj3lmmup0pvnt80fa.apps.googleusercontent.com',
    iosBundleId: 'com.claimsexpress.eSurvey',
  );
}
